// <auto-generated />
using System;
using ContractManagement.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContractManagement.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617061349_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContractManagement.API.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 15000m,
                            ClientName = "Acme Corporation",
                            CreatedAt = new DateTime(2026, 6, 12, 6, 13, 48, 886, DateTimeKind.Utc).AddTicks(3882),
                            Description = "Website Development Project",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 25000m,
                            ClientName = "TechStart Solutions",
                            CreatedAt = new DateTime(2026, 6, 7, 6, 13, 48, 886, DateTimeKind.Utc).AddTicks(3895),
                            Description = "Mobile App Development",
                            Status = "Approved"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 8000m,
                            ClientName = "Global Finance Inc",
                            CreatedAt = new DateTime(2026, 6, 14, 6, 13, 48, 886, DateTimeKind.Utc).AddTicks(3897),
                            Description = "Security Audit",
                            Status = "Declined"
                        });
                });

            modelBuilder.Entity("ContractManagement.API.Models.ServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountZAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExchangeRateUsed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ServiceRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountUSD = 5000m,
                            AmountZAR = 97500m,
                            CompletedAt = new DateTime(2026, 6, 12, 6, 13, 48, 886, DateTimeKind.Utc).AddTicks(4089),
                            ContractId = 2,
                            CreatedAt = new DateTime(2026, 6, 9, 6, 13, 48, 886, DateTimeKind.Utc).AddTicks(4088),
                            Description = "Initial delivery of mobile app",
                            ExchangeRateUsed = 19.50m,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            AmountUSD = 3000m,
                            AmountZAR = 58500m,
                            ContractId = 2,
                            CreatedAt = new DateTime(2026, 6, 14, 6, 13, 48, 886, DateTimeKind.Utc).AddTicks(4095),
                            Description = "Second phase: UI improvements",
                            ExchangeRateUsed = 19.50m,
                            Status = "InProgress"
                        });
                });

            modelBuilder.Entity("ContractManagement.API.Models.ServiceRequest", b =>
                {
                    b.HasOne("ContractManagement.API.Models.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });
#pragma warning restore 612, 618
        }
    }
}
